config/routes.rb
Rails.application.routes.draw do
  get 'rooms/index'
  get 'ivents/index'
  get 'familys/index'
  get 'ofices/index'
  devise_for :users
  root to: "topics#index"
  resources :users
  resources :themes
  resources :top, only: :index

  resources :list, only:[:new,:create,:edit,:update,:destroy]do
  resources :card, except:[:index]
  end

  resources :familys, only: :index
  resources :ofices, only: :index
  resources :ivents, only: :index
  resources :records do
    collection do
      get 'search'
    end
  end

  resources :pics do
    collection do
      get 'search'
    end
  end
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  has_one_attached :image
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :list
  has_one_attached :image

  validates :title, presence: true
 
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :cards, dependent: :destroy
  validates :title, presence: true
end

app/models/pic.rb
class Pic < ApplicationRecord
  has_one_attached :image

  validates :title, presence: true
  validates :record_day, presence: true
  validates :image, presence: true
  belongs_to :user



  def self.search(search)
    if search != ""
      Pic.where('title LIKE(?)', "%#{search}%")
    else
      Pic.all
    end
  end
end

app/models/record.rb
class Record < ApplicationRecord

  validates :title, presence: true
  validates :record_day, presence: true
  belongs_to :user
  
  def self.search(search)
    if search != ""
      Record.where('title LIKE(?)', "%#{search}%")
    else
      Record.all
    end
  end
end

app/models/theme.rb
class Theme < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :lists, dependent: :destroy

  validates :name, presence: true, length: { maximum: 6 } 
  has_many :records
  has_many :pics
end

app/controllers/card_controller.rb
class CardController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  def new
    @card = Card.new
    @list = List.find_by(id: params[:list_id])
  end

  def create
    @list = List.find_by(id: params[:list_id])
    @card = Card.new(card_params)
    if @card.save
      redirect_to top_index_path
    else
      render action: :new
    end
  end

  def show
  end

  def edit
    @lists = List.where(user: current_user)
  end

  def update
    if @card.update_attributes(card_params)
      redirect_to top_index_path
    else
      render action: :edit
    end
  end

  def destroy
    @card.destroy
    redirect_to top_index_path
  end

  private

  def card_params
    params.require(:card).permit(:title, :memo, :list_id, :image)
  end

  def set_card
    @card = Card.find_by(id: params[:id])
  end
end

app/controllers/list_controller.rb
class ListController < ApplicationController
  before_action :set_list, only: [:edit, :update, :destroy]

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to top_index_path
    else
      render action: :new
    end
  end

  def edit
  end

  def update
    if @list.update_attributes(list_params)
      redirect_to top_index_path
    else
      render action: :edit
    end
  end

  def destroy
    @list.destroy
    redirect_to top_index_path
  end

  private

  def list_params
    params.require(:list).permit(:title).merge(user: current_user)
  end

  def set_list
    @list = List.find_by(id: params[:id])
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @lists = List.where(user: current_user).order('created_at ASC')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/card_helper.rb
module CardHelper
end

app/helpers/familys_helper.rb
module FamilysHelper
end

app/helpers/ivents_helper.rb
module IventsHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/ofices_helper.rb
module OficesHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/top/index.html.erb
<header class="header">
      <nav class="nav">
        <ul class="header_menu">
          <li class="header_menu_title"><%= link_to "ONLINE SUPPORT", root_path, class: "nav-link" %></li>
          <li class="nav-link"><%= current_user.name %>さん</li>
          <li><%= link_to "リストを作成する", new_list_path, class: "nav-link listNew" %></li>
          <li><%= link_to "議事録一覧", records_path, class: "nav-link listNew" %></li>
          <li><%= link_to "サインアウト", destroy_user_session_path, class: "nav-link", method: :delete %></li>

        </ul>
           </ul>
          </li>
        </ul>
      </nav>
    </header>
     <script>
      function updateClock() {
        var now = new Date();
        var hour = now.getHours();
        var minute = now.getMinutes();
        var second = now.getSeconds();
        if ( hour < 10 ) hour = "0" + hour;
        if ( minute < 10 ) minute = "0" + minute;
        if ( second < 10 ) second = "0" + second;
        document.getElementById('myClock').innerHTML = hour+":"+minute+":"+second;
      }
      function start() {
        setInterval("updateClock();", 1000);
        updateClock();
      }
    </script>

<div class="topPage">
  <div class="listWrapper">
    <% @lists.each do |list| %>
      <div class="list">
        <div class="list_header">
          <h2 class="list_header_title"><%= list.title %></h2>
          <div class="list_header_action">
            <%= link_to content_tag(:i, '', class: 'fas fa-trash'), list, method: :delete, data: { confirm: "#{list.title}を削除して大丈夫ですか？" } %>
            <%= link_to(content_tag(:i, '', class: 'fas fa-pen'), edit_list_path(list)) %>
          </div>
        </div>


        <div class="cardWrapper">
          <% list.cards.each do |card| %>

           
            <%= link_to  list_card_path(list.id, card.id), class:"cardDetail_link" do %>
            
              <div class="card">
                <h3 class="card_title"><%= card.title %></h3>
                <% if card.memo.size > 0 %>
                <div class="card_detail is-exist" > <i class="fas fa-bars"></i></div>
                <% end %>
              </div>
            <% end %>
          
          
          <% end %>

          <div class="addCard">
            <i class="far fa-plus-square"></i>
            <%= link_to "さらにカードを追加", new_list_card_path(list.id), class: "addCard_link" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
   <div class="stopwatch"> 
  
    <div class=""><h5>時計機能</h5>
     <%= image_tag "1513420118.png", class:'issu_pic'%>
 <body onload="start();">
<div class=time id="myClock" align="center">
      
</div>

  </div>
   <div class="date">
   <div class=""><h5>会議日程調整</h5></div>
  
   <input type="date">
  </div>

 
 <div class="memos">
<div class=format><h5>会議の流れ</h5></div>
<div class="memo_top">
 <ul id="memos"></ul>
 </div>
<div class="memo">
<input type="text" id="new-todo"><button id="add-button">add</button>
 </div>