config/routes.rb
Rails.application.routes.draw do
  get 'rooms/index'
  get 'ivents/index'
  get 'familys/index'
  get 'ofices/index'
  devise_for :users
  root to: "topics#index"
  resources :users
  resources :themes
  resources :top, only: :index

  resources :list, only:[:new,:create,:edit,:update,:destroy]do
  resources :card, except:[:index]
  end

  resources :familys, only: :index
  resources :ofices, only: :index
  resources :ivents, only: :index
  resources :records do
    collection do
      get 'search'
    end
  end

  resources :pics do
    collection do
      get 'search'
    end
  end
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  has_one_attached :image
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :list
  has_one_attached :image

  validates :title, presence: true
 
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :cards, dependent: :destroy
  validates :title, presence: true
end

app/models/pic.rb
class Pic < ApplicationRecord
  has_one_attached :image

  validates :title, presence: true
  validates :record_day, presence: true
  validates :image, presence: true
  belongs_to :user



  def self.search(search)
    if search != ""
      Pic.where('title LIKE(?)', "%#{search}%")
    else
      Pic.all
    end
  end
end

app/models/record.rb
class Record < ApplicationRecord

  validates :title, presence: true
  validates :record_day, presence: true
  belongs_to :user
  
  def self.search(search)
    if search != ""
      Record.where('title LIKE(?)', "%#{search}%")
    else
      Record.all
    end
  end
end

app/models/theme.rb
class Theme < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :lists, dependent: :destroy

  validates :name, presence: true, length: { maximum: 6 } 
  has_many :records
  has_many :pics
end

app/controllers/card_controller.rb
class CardController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  def new
    @card = Card.new
    @list = List.find_by(id: params[:list_id])
  end

  def create
    @list = List.find_by(id: params[:list_id])
    @card = Card.new(card_params)
    if @card.save
      redirect_to top_index_path
    else
      render action: :new
    end
  end

  def show
  end

  def edit
    @lists = List.where(user: current_user)
  end

  def update
    if @card.update_attributes(card_params)
      redirect_to top_index_path
    else
      render action: :edit
    end
  end

  def destroy
    @card.destroy
    redirect_to top_index_path
  end

  private

  def card_params
    params.require(:card).permit(:title, :memo, :list_id, :image)
  end

  def set_card
    @card = Card.find_by(id: params[:id])
  end
end

app/controllers/list_controller.rb
class ListController < ApplicationController
  before_action :set_list, only: [:edit, :update, :destroy]

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to top_index_path
    else
      render action: :new
    end
  end

  def edit
  end

  def update
    if @list.update_attributes(list_params)
      redirect_to top_index_path
    else
      render action: :edit
    end
  end

  def destroy
    @list.destroy
    redirect_to top_index_path
  end

  private

  def list_params
    params.require(:list).permit(:title).merge(user: current_user)
  end

  def set_list
    @list = List.find_by(id: params[:id])
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: [:show, :edit, :update, :destroy]
 

  def index
    @records =current_user.records
  end

  def new
    @record = Record.new
  end

  def create
    @record = Record.new(record_params)
    if @record.save
      redirect_to records_path
    else
      render action: :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @record.update_attributes(record_params)
      redirect_to records_path
    else
      render action: :edit
    end
  end

  def destroy
    @record.destroy
    redirect_to records_path
  end

  def search
    @records = Record.search(params[:keyword])
  end

  private

  def record_params
    params.require(:record).permit(:title, :memo,:image,:record_day).merge(user_id: current_user.id)
  end

  def set_record
    @record = Record.find_by(id: params[:id])
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @lists = List.where(user: current_user).order('created_at ASC')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/card_helper.rb
module CardHelper
end

app/helpers/familys_helper.rb
module FamilysHelper
end

app/helpers/ivents_helper.rb
module IventsHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/ofices_helper.rb
module OficesHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/records/_navi.html.erb
<header class="header">
      <nav class="nav">
        <ul class="header_menu">
          <li class="header_menu_title"><%= link_to "ONLINE SUPPORT", root_path, class: "nav-link" %></li>
          <li class="nav-link"><%= current_user.name %>さん</li>
          <li><%= link_to "リストを作成", new_list_path, class: "nav-link listNew" %></li>
          <li><%= link_to "議事録一覧", records_path, class: "nav-link listNew" %></li>
          <li><%= link_to "サインアウト", destroy_user_session_path, class: "nav-link", method: :delete %></li>

        </ul>
           </ul>
          </li>
        </ul>
      </nav>
</header>

app/views/records/edit.html.erb
<header class="header">
      <nav class="nav">
        <ul class="header_menu">
          <li class="header_menu_title"><%= link_to "ONLINE SUPPORT", root_path, class: "nav-link" %></li>
          <li class="nav-link"><%= current_user.name %>さん</li>
          <li><%= link_to "リストに戻る",top_index_path , class: "nav-link listNew" %></li>
          <li><%= link_to "議事録一覧", records_path, class: "nav-link listNew" %></li>
          <li><%= link_to "サインアウト", destroy_user_session_path, class: "nav-link", method: :delete %></li>

        </ul>
           </ul>
          </li>
        </ul>
      </nav>
 </header>
<div class="cardeditPgae">
  <div class='contain'>
    <%= form_with model: @record, url: { action: :update }, html: { class: 'cardeditForm' }, local: true do |f| %>
      <% if @record.errors.any? %>
        <p class="text-danger">タイトルは1～255文字以内で入力してください</p>
      <% end %>
      <div class="cardeditForm_title">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control", placeholder: "カード名" %>
      </div>
      <div class="cardeditForm_memo">
        <%= f.label :memo %>
        <%= f.text_area :memo, class: "form-control", placeholder: "詳細" %>
      </div>
      <div class="img-upload">
          <div class="weight-bold-text">
            添付資料
          </div>
          <div class="click-upload">
            <%= f.file_field :image, id:"item-image" %>
            <div class="preview" id="image-list">
            

        </div>
      
      <div class="text-center"><%= f.submit "更新する", class: "submitBtn" %></div>
    <% end %>
  </div>
</div>

app/views/records/index.html.erb
<header class="header">
      <nav class="nav">
        <ul class="header_menu">
          <li class="header_menu_title"><%= link_to "ONLINE SUPPORT", root_path, class: "nav-link" %></li>
          <li class="nav-link"><%= current_user.name %>さん</li>
          <li><%= link_to "議事録を作成", new_record_path, class: "nav-link listNew" %></li>
          <li><%= link_to "サインアウト", destroy_user_session_path, class: "nav-link", method: :delete %></li>

        </ul>
           </ul>
          </li>
        </ul>
      </nav>
 </header>

<div class="Form">
   <h6>議事録</h6>
   <div class="serch">
<%= form_with(url: search_records_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "議事録を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-bt" %>
  </div>
<% end %>        
    <%  @records.each do |record| %>
        <div class="record_action">
            <%= link_to content_tag(:i, '', class: 'fas fa-trash'), record, method: :delete %>
            <%= link_to(content_tag(:i, '', class: 'fas fa-pen'), edit_record_path(record)) %>
        </div>
        <div class="records">
        <div class="record_pic"> 
        <%= image_tag record.image.variant(resize: '800x900'), class: 'message' if record.image.attached? %>
        </div>
        <div class="Form-Item">
          <p class="Form-Item-Label">■議題
          </p>
          <%= record.title %>
        </div>
        <div class="Form-Item">
          <p class="Form-Item-Label">■会議日</p>
          <div><%= record.record_day %></div>

        </div>
        <div class="Form-Item">
          <p class="Form-Item-Label isMsg">■■メモ</p>
          <div><%= record.memo %></div>
        </div>
        </div> 
        <hr class="cp_hr04" />
   <%end%> 

</div>

app/views/records/new.html.erb
<header class="header">
      <nav class="nav">
        <ul class="header_menu">
          <li class="header_menu_title"><%= link_to "ONLINE SUPPORT", root_path, class: "nav-link" %></li>
          <li class="nav-link"><%= current_user.name %>さん</li>
          <li><%= link_to "リストに戻る",top_index_path , class: "nav-link listNew" %></li>
          <li><%= link_to "議事録一覧", records_path, class: "nav-link listNew" %></li>
          <li><%= link_to "サインアウト", destroy_user_session_path, class: "nav-link", method: :delete %></li>

        </ul>
           </ul>
          </li>
        </ul>
      </nav>
 </header>
<div class="cardnewPgae">
  <div class='container'>
    <%= form_with model: @record, url: { action: :create }, html: { class: 'cardnewForm' }, local: true do |f| %>
      
      <div class="cardnewForm_title">
        <%= f.label :title %>
        <span class="indispensable">必須</span>
        <%= f.text_field :title, autofocus: true, class: "form-control", placeholder: "カード名" %>
      </div>
      <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">会議の日程</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-birth-wrap'>
      <%= raw sprintf(
                  f.date_select(
                    :record_day,
                    class:'select-birth',
                    id:"birth-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: 2000,
               
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
    </div>

      <div class="cardnewForm_memo">
        <%= f.label :memo %>
         <span class="indispensable">必須</span>
        <%= f.text_area :memo, autofocus: true, class: "form-control", placeholder: "詳細" %>
        </div>
       
      <div class="img-upload">
          <div class="weight-bold-text">
            添付資料
          </div>
          <div class="click-upload">
            <%= f.file_field :image, id:"item-image" %>
          </div>
          <div class="image-list" id="image-list">
          </div>
           


        </div>


      <div class="text-center"><%= f.submit "作成する", class: "submitBtn" %></div>
      </div>
      

    <% end %>
  </div>
</div>

app/views/records/search.html.erb
 <header class="header">
      <nav class="nav">
        <ul class="header_menu">
          <li class="header_menu_title"><%= link_to "kanban", root_path, class: "nav-link" %></li>
          <li class="nav-link"><%= current_user.name %>さん</li>
          <li><%= link_to "リストを作成", new_list_path, class: "nav-link listNew" %></li>
          <li><%= link_to "議事録一覧", records_path, class: "nav-link listNew" %></li>
          <li><%= link_to "サインアウト", destroy_user_session_path, class: "nav-link", method: :delete %></li>

        </ul>
           </ul>
          </li>
        </ul>
      </nav>
    </header>

 
 <div class="search">

 <h6>検索結果の表示</h6>

  </div>

<div class="contents row">
   <% @records.each do |record| %>
        <div class="header_action">
            <%= link_to content_tag(:i, '', class: 'fas fa-trash'), record, method: :delete %>
            <%= link_to(content_tag(:i, '', class: 'fas fa-pen'), edit_record_path(record)) %>
          </div>
        <div class="records">
        <div class="record_pic"> 
        <%= image_tag record.image.variant(resize: '700x900'), class: 'message-image' if record.image.attached? %>
        </div>
        <div class="Form-Item">
          <p class="Form-Item-Label">■議題
          </p>
          <%= record.title %>
        </div>
        <div class="Form-Item">
          <p class="Form-Item-Label">■会議日</p>
          <div><%= record.record_day %></div>

        </div>
        <div class="Form-Item">
          <p class="Form-Item-Label isMsg">■■メモ</p>
          <div><%= record.memo %></div>
        </div>
        </div> 
        <hr class="cp_hr04" />
  <% end %>
</div>