config/routes.rb
Rails.application.routes.draw do
  get 'rooms/index'
  get 'ivents/index'
  get 'familys/index'
  get 'ofices/index'
  devise_for :users
  root to: "topics#index"
  resources :users
  resources :themes
  resources :top, only: :index

  resources :list, only:[:new,:create,:edit,:update,:destroy]do
  resources :card, except:[:index]
  end

  resources :familys, only: :index
  resources :ofices, only: :index
  resources :ivents, only: :index
  resources :records do
    collection do
      get 'search'
    end
  end

  resources :pics do
    collection do
      get 'search'
    end
  end
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  has_one_attached :image
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :list
  has_one_attached :image

  validates :title, presence: true
 
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :cards, dependent: :destroy
  validates :title, presence: true
end

app/models/pic.rb
class Pic < ApplicationRecord
  has_one_attached :image

  validates :title, presence: true
  validates :record_day, presence: true
  validates :image, presence: true
  belongs_to :user



  def self.search(search)
    if search != ""
      Pic.where('title LIKE(?)', "%#{search}%")
    else
      Pic.all
    end
  end
end

app/models/record.rb
class Record < ApplicationRecord

  validates :title, presence: true
  validates :record_day, presence: true
  belongs_to :user
  
  def self.search(search)
    if search != ""
      Record.where('title LIKE(?)', "%#{search}%")
    else
      Record.all
    end
  end
end

app/models/theme.rb
class Theme < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :lists, dependent: :destroy

  validates :name, presence: true, length: { maximum: 6 } 
  has_many :records
  has_many :pics
end

app/controllers/card_controller.rb
class CardController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  def new
    @card = Card.new
    @list = List.find_by(id: params[:list_id])
  end

  def create
    @list = List.find_by(id: params[:list_id])
    @card = Card.new(card_params)
    if @card.save
      redirect_to top_index_path
    else
      render action: :new
    end
  end

  def show
  end

  def edit
    @lists = List.where(user: current_user)
  end

  def update
    if @card.update_attributes(card_params)
      redirect_to top_index_path
    else
      render action: :edit
    end
  end

  def destroy
    @card.destroy
    redirect_to top_index_path
  end

  private

  def card_params
    params.require(:card).permit(:title, :memo, :list_id, :image)
  end

  def set_card
    @card = Card.find_by(id: params[:id])
  end
end

app/controllers/list_controller.rb
class ListController < ApplicationController
  before_action :set_list, only: [:edit, :update, :destroy]

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to top_index_path
    else
      render action: :new
    end
  end

  def edit
  end

  def update
    if @list.update_attributes(list_params)
      redirect_to top_index_path
    else
      render action: :edit
    end
  end

  def destroy
    @list.destroy
    redirect_to top_index_path
  end

  private

  def list_params
    params.require(:list).permit(:title).merge(user: current_user)
  end

  def set_list
    @list = List.find_by(id: params[:id])
  end
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
    before_action :set_pic, only: [:show, :edit, :update, :destroy]
   
  
    def index
      @pics=current_user.pics
    end
  
    def new
      @pic = Pic.new
    end
  
    def create
      @pic= Pic.new(pics_params)
      if  @pic.save
        redirect_to pics_path
      else
        render action: :new
      end
    end


  
    def show
    end
  
    def edit
    end
  
    def update
      if @pic.update_attributes(pics_params)
        redirect_to pics_path
      else
        render action: :edit
      end
    end
  
    def destroy
      @pic.destroy
      redirect_to pics_path
    end

  
    def search
      @pics= Pic.search(params[:keyword])
    end
  
    private
    def pics_params
      params.require(:pic).permit(:title, :memo,:image,:record_day).merge(user_id: current_user.id)
    end
    
    def set_pic
      @pic = Pic.find_by(id: params[:id])
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @lists = List.where(user: current_user).order('created_at ASC')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/card_helper.rb
module CardHelper
end

app/helpers/familys_helper.rb
module FamilysHelper
end

app/helpers/ivents_helper.rb
module IventsHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/ofices_helper.rb
module OficesHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/card/edit.html.erb
<div class="cardeditPgae">
  <div class='container'>
    <%= form_with model: @card, url: { action: :update }, html: { class: 'cardeditForm' }, local: true do |f| %>
      <% if @card.errors.any? %>
        <p class="text-danger">タイトルは1～255文字以内で入力してください</p>
      <% end %>
      <div class="cardeditForm_title">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control", placeholder: "カード名" %>
      </div>
      <div class="cardeditForm_memo">
        <%= f.label :memo %>
        <%= f.text_area :memo, class: "form-control", placeholder: "詳細" %>
      </div>
      <div class="img-upload">
          <div class="weight-bold-text">
            添付資料
          </div>
          <div class="click-upload">
            <%= f.file_field :image, id:"item-image" %>
            <div class="preview" id="image-list">
            </div>

        </div>
      <div class="cardeditForm_memo">
        <label>仕事を振り分け先</label>
        <%= select :card, :list_id, @lists.map{ |l| [l.title, l.id] }, {}, { class: 'form-control' } %>
      </div>
      <div class="text-center"><%= f.submit "更新する", class: "submitBtn" %></div>
    <% end %>
  </div>
</div>

app/views/card/new.html.erb
<div class="cardnewPgae">
  <div class='container'>
    <%= form_with model: @card, url: { action: :create }, html: { class: 'cardnewForm' }, local: true do |f| %>
      <%= f.hidden_field :list_id, value: @list.id %>
      <% if @card.errors.any? %>
        <p class="text-danger">タイトルは1～255文字以内で入力してください</p>
      <% end %>
      <div class="cardnewForm_title">
        <%= f.label :title %>
        <span class="indispensable">必須</span>
        <%= f.text_field :title, autofocus: true, class: "form-control", placeholder: "カード名" %>
      </div>
      <div class="cardnewForm_memo">
        <%= f.label :memo %>
         <span class="indispensable">必須</span>
        <%= f.text_area :memo, autofocus: true, class: "form-control", placeholder: "詳細" %>
        </div>
       
      <div class="img-upload">
          <div class="weight-bold-text">
            添付資料
          </div>
          <div class="click-upload">
            <%= f.file_field :image, id:"item-image" %>
          </div>
          <div id="image-list"></div>
           


        </div>


      <div class="text-center"><%= f.submit "作成する", class: "submitBtn" %></div>
      </div>
      

    <% end %>
  </div>
</div>

app/views/card/show.html.erb
<div class='carddetailPage'>
  <div class="container">
    <div class="cardContents">
      <div class="cardContents_title">
        <div>タイトル</div>
        <h2><%= @card.title %></h2>
      </div>
      <div class="cardContents_memo">
        <div>メモ</div>
        <div><%= @card.memo %></div>
      </div>
      <div class="cardContents_listStatus">
        <div>リスト名</div>
        <div><%= @card.list.title %></div>
      </div>
      <div class="cardContents_listStatus">
        <div>画像</div>
          <%= image_tag @card.image.variant(resize: '500x500'), class: 'message-image' if @card.image.attached? %>
          
      </div>



      <div class="cardContents_btnArea">
      <%= link_to '仕事を振り分ける', edit_list_card_path(@card.list, @card), class: "edit_btn" %>
     </br>
     <%= link_to '削除をする', list_card_path(@card.list, @card), class: "delete_btn", method: :delete, data: { confirm: "このカードを削除して大丈夫ですか?" } %>
      </div>
    </div>
  </div>
</div>

app/views/list/edit.html.erb
<div class="listeditPage">
  <div class="container">
    <%= form_with model: @list, url: { action: :update }, html: { class: 'listForm' }, local: true do |f| %>
      <% if @list.errors.any? %>
        <p class="text-danger">タイトルは1～255文字以内で入力してください</p>
      <% end %>
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control listName", placeholder: "リスト名" %>
      
      <div class="text-center"><%= f.submit "編集する", class: "submitBtn" %></div>
    <% end %>
  </div>
</div>

app/views/list/new.html.erb
<div class="listnewPage">
  <div class="container">
    <%= form_with model: @list, url: { action: :create }, class: "new_list", local: true do |f| %>
      <% if @list.errors.any? %>
        <p class="text-danger">タイトルは1～255文字以内で入力してください</p>
      <% end %>
      <%= f.label :title %>
      <%= f.text_field :title, autofocus: true, class: "form-control listName", placeholder: "リスト名" %>
      <div class="text-center"><%= f.submit "作成", class: "submitBtn" %></div>
    <% end %>
  </div>
</div>